var express = require('express');
var router = express.Router();
var DatabaseFacade = require('../Data/DatabaseFacade');

/**
 * Deletes student by email
 * @param {String} studentID-  The object id of the student to delete
 * Returns status code 200 if success.    
 * Returns staus code 500 if failed to delete the student
 */
router.delete('/delete/:studentID', async (req, res, next) => {
  var studentID = req.params.studentID;
  try {
    result = await DatabaseFacade.deleteStudentByID(studentID);
  } catch (r) {
    result = null;
  }
  if (result !== null) {
    res.status(200).send("Success!");
  }
  else {
    res.status(500).send("Failed to delete student ");
  }
});

/* *///
/**
 * checks login info and returns all messages for that student. 
 *  @param {String} mail - the students mail     
 *  @param {String}  token- pushtoken generated by expo
 * Todo: change to post 
 * 
 */
router.get('/login/:studentMail/:token', async (req, res, next) => {

  var studentMail = req.params.studentMail.toLowerCase();
  var token = req.params.token;
  try {
    await DatabaseFacade.setStudentToken(studentMail, token)
    result = await DatabaseFacade.getStudentByMail(studentMail);
  }
  catch (r) {
    result = null;
  }
  if (result !== null) {
    res.json(result);
  }
  else {
    res.status(500).send("The mail does not match!");
  }
});


module.exports = router;
